#!/usr/bin/env python3
"""Generate thin agent wrappers from the canonical skills in .agents/skills/.

Codex, OpenCode and Gemini CLI read .agents/skills/ directly. Claude Code reads
.claude/skills/, and Gemini CLI slash commands live in .gemini/commands/.
This script writes one wrapper per skill that points back to the canonical
SKILL.md, so the instructions exist in exactly one place.

Usage:
    python tools/sync_agent_wrappers.py          # write wrappers
    python tools/sync_agent_wrappers.py --check  # exit 1 if wrappers are stale

Standard library only.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / ".agents" / "skills"
CLAUDE = ROOT / ".claude" / "skills"
GEMINI = ROOT / ".gemini" / "commands"
HEADER = "Generated by tools/sync_agent_wrappers.py from .agents/skills/{name}/SKILL.md. Do not edit."


def read_frontmatter(path: Path) -> dict[str, str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{path}: missing frontmatter")
    meta: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            return meta
        key, sep, value = line.partition(":")
        if sep:
            meta[key.strip()] = value.strip()
    raise ValueError(f"{path}: unterminated frontmatter")


def claude_wrapper(name: str, description: str) -> str:
    return (
        f"---\nname: {name}\ndescription: {description}\n---\n\n"
        f"<!-- {HEADER.format(name=name)} -->\n\n"
        f"Read `.agents/skills/{name}/SKILL.md` and follow it exactly. "
        f"That file is the canonical version of this skill.\n\n"
        f"User input: $ARGUMENTS\n"
    )


def gemini_wrapper(name: str, description: str) -> str:
    desc = description.replace("\\", "\\\\").replace('"', '\\"')
    return (
        f"# {HEADER.format(name=name)}\n"
        f'description = "{desc}"\n'
        f'prompt = """\n'
        f"Read the file `.agents/skills/{name}/SKILL.md` in this repository and follow it exactly.\n\n"
        f"User input: {{{{args}}}}\n"
        f'"""\n'
    )


def main() -> int:
    check = "--check" in sys.argv[1:]
    expected: dict[Path, str] = {}
    for skill_md in sorted(SKILLS.glob("*/SKILL.md")):
        meta = read_frontmatter(skill_md)
        name, description = meta.get("name"), meta.get("description")
        if not name or not description:
            print(f"error: {skill_md} needs name and description", file=sys.stderr)
            return 1
        if name != skill_md.parent.name:
            print(f"error: {skill_md}: name '{name}' must match its folder", file=sys.stderr)
            return 1
        expected[CLAUDE / name / "SKILL.md"] = claude_wrapper(name, description)
        expected[GEMINI / f"{name}.toml"] = gemini_wrapper(name, description)

    stale = [p for p, text in expected.items()
             if not p.exists() or p.read_text(encoding="utf-8") != text]
    if check:
        for p in stale:
            print(f"stale: {p.relative_to(ROOT)}")
        return 1 if stale else 0
    for p in stale:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(expected[p], encoding="utf-8", newline="\n")
        print(f"wrote {p.relative_to(ROOT)}")
    print(f"{len(expected) // 2} skills, {len(stale)} wrapper(s) updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
